version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - network1
    # restart: on-failure COMMENTED FOR DEBUGGING
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

# volumes:
#   DB: 

networks:
  network1:
    driver: bridge
