version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - network1
    restart: on-failure
    volumes:
      - DB:/var/lib/mysql/

volumes:
  DB:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb/
    

networks:
  network1:
    driver: bridge
