version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    networks:
      - network1
    restart: on-failure
    volumes:
      - WPDB:/var/www
    ports:
      - 80:80
    depends_on:
        - wordpress
    

  wordpress:
      build: requirements/wordpress/
      container_name: wordpress
      networks:
        - network1
      restart: on-failure
      volumes:
        - WPDB:/var/www
      depends_on:
        - mariadb

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - network1
    restart: on-failure
    volumes:
      - DB:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  DB: 
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb
  WPDB: 
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress

networks:
  network1:
    driver: bridge
